export const parameters = Object.freeze({
  areasTecnicas: Object.freeze([
    "Assistência Social",
    "Central de Dados",
    "Consórcios Públicos",
    "Contabilidade",
    "Cultura",
    "Desenvolvimento Rural",
    "Educação",
    "Estudos Técnicos",
    "Finanças",
    "Jurídico",
    "Meio Ambiente",
    "Mulheres",
    "Obras e Transf. da União",
    "Orçamento",
    "Planej. Territ.  e Habitação",
    "Previdência",
    "Proteção e Defesa Civil",
    "Saneamento",
    "Saúde",
    "Segurança Pública",
    "Transporte e Mobilidade",
    "Turismo"
  ]),
  responsaveis: Object.freeze([
    "Alessandra Ferreira (Colaborador)",
    "Alex Carneiro (Colaborador)",
    "Ana Clara Elias (Colaborador)",
    "Aquila Ferreira (Colaborador)",
    "Arthur Trindade (Consultor)",
    "Augusto Fortunato (Colaborador)",
    "Beatriz Silva (Colaborador)",
    "Brunno Trindade (Colaborador)",
    "Carlos Silva  (Colaborador)",
    "Caroline Hoss (Consultor)",
    "Cláudia Lima (Colaborador)",
    "Cleide Pompermaier (Consultor)",
    "Dayane Santos (Colaborador)",
    "Denilson Magalhães (Consultor)",
    "Eduardo Santana (Colaborador)",
    "Eduardo Stranz (Consultor)",
    "Elena Garrido (Consultor)",
    "Eliane Henriques (Colaborador)",
    "Elisa Schoenell (Consultor)",
    "Elisângela Fernandes (Consultor)",
    "Eudes Sippel (Consultor)",
    "Eugênio Greggianin (Consultor)",
    "Fernanda Fernandes (Consultor)",
    "Filipe Landim (Colaborador)",
    "Flavia Salvador (Colaborador)",
    "Gil Castello Branco (Consultor)",
    "Guilherme Krieger (Consultor)",
    "Hernany Reis (Colaborador)",
    "Hilton Silva (Colaborador)",
    "Ingrid Lima (Colaborador)",
    "Jaqueline Silva (Colaborador)",
    "Joanni Henrichs (Consultor)",
    "João de Sá (Colaborador)",
    "Johnny Liberato (Colaborador)",
    "Jordan Cabral (Colaborador)",
    "Karla França (Colaborador)",
    "Leonardo Rolim (Consultor)",
    "Leyliane Sena (Colaborador)",
    "Lorranny Xavier (Colaborador)",
    "Luan Guerson (Colaborador)",
    "Lucas Silva (Colaborador)",
    "Marcus Santos (Colaborador)",
    "Mário Nascimento (Consultor)",
    "Mário Rattes (Consultor)",
    "Mariza Abreu (Consultor)",
    "Marta Rodrigues (Colaborador)",
    "Martin Haeberlin (Consultor)",
    "Martin Schulze (Consultor)",
    "Max Aroldi (Consultor)",
    "Michelle Paionk (Colaborador)",
    "Midya Souza (Colaborador)",
    "Mônica Costa (Colaborador)",
    "Nancy Ramos (Consultor)",
    "Natasha Comassetto (Consultor)",
    "Osni Rocha (Colaborador)",
    "Pamela Santos (Colaborador)",
    "Paulo Caliendo (Consultor)",
    "Pedro Passos (Consultor)",
    "Priscila Kaiser (Consultor)",
    "Rafael Correa (Consultor)",
    "Raquel Silva (Colaborador)",
    "Renan Rocha (Colaborador)",
    "Ricardo Hermany (Consultor)",
    "Rita Bartole (Colaborador)",
    "Roberto Siegmann (Consultor)",
    "Rodrigo Dias (Colaborador)",
    "Rosângela Ribeiro (Consultor)",
    "Sabrina Souza (Consultor)",
    "Sandoval Neto (Colaborador)",
    "Sérgio Gobetti (Consultor)",
    "Simone Macedo (Consultor)",
    "Thais Lima Mendes (Colaborador)",
    "Thiago Oliveira (Colaborador)",
    "Valdery Brito (Consultor)",
    "Valtuir Nunes (Consultor)",
    "Vinicius Almeida (Colaborador)",
    "Vitória Jadallah (Colaborador)",
    "Wanderson Rocha (Colaborador)",
    "Zacarias Sousa (Colaborador)",
    "Zuilla Lima (Colaborador)"
  ]),
  pareceres: Object.freeze(["Sim", "Não", "Em andamento"]),
  emendas: Object.freeze(["Sim", "Não"]),
  posicionamentos: Object.freeze(["Favorável", "Desfavorável", "Indiferente"])
});

export const recordFields = Object.freeze([
  "areaTecnica",
  "responsavel",
  "projeto",
  "ementa",
  "atualComissao",
  "haParecer",
  "sugestaoEmenda",
  "posicionamento"
]);
