// Catálogo oficial da Câmara: /api/v2/referencias/proposicoes/siglaTipo (2026-10-01).
// Algumas linhas da API compartilham a mesma sigla; a busca usa a sigla, então basta uma descrição por código.
export const propositionTypes = Object.freeze([
  ["AA","Autógrafo"],
  ["ADD","Adendo"],
  ["AJECN","Ajuste de Emenda Orçamentária (CN)"],
  ["ANEXO","Anexo"],
  ["APJ","Anteprojeto"],
  ["APM","Complemento de Apoiamento"],
  ["ATA","Ata"],
  ["ATA_PRE","Ata Preparatória"],
  ["ATACN","Ata (CN)"],
  ["ATC","Ato Convocatório"],
  ["AV","Demonstrativo de emissão do real"],
  ["AVN","Aviso (CN)"],
  ["CAC","Comunicado de Alteração do Controle Societário"],
  ["CAE","Relatório de Atividades do Comitê de Admissibilidade de Emendas (CAE)"],
  ["CCN","Consulta do Congresso Nacional"],
  ["CFIS","Relatório de Atividades do Comitê de Avaliação, Fiscalização e Controle de Execução Orçamentária"],
  ["CMC","Comunicação de Medida Cautelar"],
  ["COI","Relatório do COI"],
  ["CON","Consulta"],
  ["CRVITAEDOC","Curriculum Vitae/Outro Documento"],
  ["CST","Solicitação de Pronunciamento"],
  ["CVO","Complementação de Voto"],
  ["CVR","Contestação ao Voto do Relator"],
  ["DCR","Denúncia por Crime de Responsabilidade"],
  ["DEC","Decisão"],
  ["DEF","Defesa Escrita"],
  ["DEN","Denúncia"],
  ["DIS","Discurso"],
  ["DOC","Documento"],
  ["DOCCPI","Documento de CPI"],
  ["DTN","Destaque (CN)"],
  ["DTQ","Destaque"],
  ["DTS","Destaque Simples"],
  ["DVT","Declaração de Voto"],
  ["EAG","Emenda Substitutiva Aglutinativa Global"],
  ["ECN","Emenda (CN)"],
  ["EMA","Emenda Aglutinativa"],
  ["EMC","Emenda na Comissão"],
  ["EMC-A","Emenda Adotada pela Comissão"],
  ["EMD","Emenda"],
  ["EML","Emenda à LDO"],
  ["EMO","Emenda ao Orçamento"],
  ["EMP","Emenda de Plenário"],
  ["EMPV","Emenda à Medida Provisória (CN)"],
  ["EMR","Emenda de Relator"],
  ["EMRP","Emenda de Relator Parcial"],
  ["EMS","Emenda/Substitutivo do Senado"],
  ["EPP","Emenda ao Plano Plurianual"],
  ["ERD","Emenda de Redação"],
  ["ERD-A","Emenda de Redação Adotada"],
  ["ERR","Errata"],
  ["ESB","Emenda ao Substitutivo"],
  ["ESP","Emenda Substitutiva de Plenário"],
  ["IAN","Indicação da ANC (1987-88)"],
  ["INA","Indicação de Autoridade"],
  ["INC","Indicação"],
  ["MAD","Manifestação do(a) Denunciado(a)"],
  ["MAN","Manifestação do Relator"],
  ["MCN","Mensagem (CN)"],
  ["MIP","Minuta de Proposição Legislativa"],
  ["MMP","Mensagem (MPU)"],
  ["MPV","Medida Provisória"],
  ["MSC","Mensagem"],
  ["MSF","Mensagem (SF)"],
  ["MSG","Mensagem (SF)"],
  ["MST","Mensagem (STF)"],
  ["MTC","Mensagem (TCU)"],
  ["NIC","Norma Interna"],
  ["OBJ","Objeto de Deliberação"],
  ["OF","Ofício do Congresso Nacional"],
  ["OFE","Ofício de Órgão do Poder Executivo"],
  ["OFJ","Ofício de Órgão do Poder Judiciário"],
  ["OFM","Ofício à Mesa"],
  ["OFN","Ofício (CN)"],
  ["OFS","Ofício do Senado Federal"],
  ["P.C","Parecer (CD)"],
  ["PAR","Parecer de Comissão"],
  ["PARF","Parecer de Comissão para Redação Final"],
  ["PCA","Parecer da ANC (1987-88)"],
  ["PDA","Projeto de Decisão da ANC (1987-88)"],
  ["PDC","Projeto de Decreto Legislativo"],
  ["PDL","Projeto de Decreto Legislativo"],
  ["PDN","Projeto de Decreto Legislativo (CN)"],
  ["PDS","Projeto de Decreto Legislativo (SF)"],
  ["PEA","Parecer à Emenda Aglutinativa"],
  ["PEC","Proposta de Emenda à Constituição"],
  ["PEP","Parecer às Emendas de Plenário"],
  ["PES","Parecer às Emendas Apresentadas ao Substitutivo do Relator"],
  ["PET","Petição"],
  ["PFC","Proposta de Fiscalização e Controle"],
  ["PIN","Proposta de Instrução Normativa"],
  ["PL","Projeto de Lei"],
  ["PLC","Projeto de Lei da Câmara dos Deputados (SF)"],
  ["PLN","Projeto de Lei (CN)"],
  ["PLP","Projeto de Lei Complementar"],
  ["PLS","Projeto de Lei do Senado Federal"],
  ["PLV","Projeto de Lei de Conversão"],
  ["PPP","Parecer Proferido em Plenário"],
  ["PPR","Parecer Reformulado de Plenário"],
  ["PR/CNJ","Parecer do Conselho Nacional de Justiça"],
  ["PR/CNMP","Parecer do Conselho Nacional do Ministério Público"],
  ["PRA","Projeto de Resolução da ANC (1987-88)"],
  ["PRC","Projeto de Resolução"],
  ["PRF","Projeto de Resolução do Senado Federal"],
  ["PRL","Parecer do Relator"],
  ["PRLE","Parecer Preliminar às Emendas de Plenário"],
  ["PRLP","Parecer Preliminar"],
  ["PRLP(V)","Parecer Preliminar Vencedor"],
  ["PRN","Projeto de Resolução do Congresso Nacional"],
  ["PRO","Proposta"],
  ["PROC","Processo Interno"],
  ["PRP","Parecer do Relator Parcial"],
  ["PRR","Parecer Reformulado"],
  ["PRST","Parecer à Redação para o Segundo Turno"],
  ["PRT","Parecer Técnico"],
  ["PRV","Parecer Vencedor"],
  ["PRVP","Proposta de Redação do Vencido em Primeiro Turno"],
  ["PSS","Parecer às Emendas ou ao Substitutivo do Senado"],
  ["QO","Questão de Ordem"],
  ["R.C","Recurso do Congresso Nacional"],
  ["RAT","Relatório Setorial"],
  ["RCEL","Relatório de Comissão de Estudo Legislativo"],
  ["RCEX","Relatório de Comissão Externa"],
  ["RCM","Requerimento de Comissão Mista"],
  ["RCP","Requerimento de Instituição de CPI"],
  ["RDF","Redação Final"],
  ["RDV","Redação do Vencido"],
  ["REC","Recurso"],
  ["REL","Relatório de Subcomissão"],
  ["REL-A","Relatório Adotado pela Comissão"],
  ["REM","Reclamação"],
  ["REP","Representação"],
  ["REQ","Requerimento"],
  ["RFP","Refomulação de Parecer - art. 130, parágrafo único do RICD."],
  ["RGT","Relatório de Grupo de Trabalho"],
  ["RIC","Requerimento de Informação"],
  ["RIN","Requerimento de Resolução Interna"],
  ["RLF","Relatório Final"],
  ["RLG","Relatório Geral"],
  ["RLP","Relatório Prévio"],
  ["RLP(R)","Relatório Prévio Reformulado"],
  ["RLP(V)","Relatório Prévio Vencedor"],
  ["RPA","Relatório Parcial"],
  ["RPD","Requerimento de Retirada da OD de proposições com pareceres favoraveis"],
  ["RPDR","Requerimento Procedimental Genérico de Sessão/Reunião"],
  ["RPL","Relatório Preliminar"],
  ["RPLE","Relatório Preliminar Apresentado com Emendas"],
  ["RPLOA","Relatório Preliminar"],
  ["RQA","Requerimento de Informações da ANC (1987-88)"],
  ["RQC","Requerimento de Convocação"],
  ["RQN","Requerimento do Congresso Nacional"],
  ["RRC","Relatório de Receita"],
  ["RRL","Relatório do Relator (CMO)"],
  ["RRR","Relatório Reformulado"],
  ["RST","Redação para o segundo turno"],
  ["RVC","Relatório Vencedor"],
  ["SAP","Sustação de Andamento de Ação Penal"],
  ["SBE","Subemenda"],
  ["SBE-A","Subemenda Adotada pela Comissão"],
  ["SBR","Subemenda de Relator"],
  ["SBT","Substitutivo"],
  ["SBT-A","Substitutivo adotado pela Comissão"],
  ["SDL","Sugestão de Emenda à LDO - CLP"],
  ["SGM","Ofício da Mesa"],
  ["SIP","Solicitação para instauração de processo"],
  ["SIT","Solicitação de Informação ao TCU"],
  ["SLD","Sugestão de Emenda à LDO - Comissões"],
  ["SOA","Sugestão de Emenda ao Orçamento - CLP"],
  ["SOR","Sugestão de Emenda ao Orçamento - Comissões"],
  ["SPA","Sugestão de Emenda ao PPA - CLP"],
  ["SPA-R","Sugestão de Emenda ao PPA - revisão (CLP)"],
  ["SPP","Sugestão de Emenda ao PPA - Comissões"],
  ["SPP-R","Sugestão de Emenda ao PPA - revisão (Comissões)"],
  ["SRL","Sugestão de Emenda a Relatório"],
  ["SSP","Subemenda Substitutiva de Plenário"],
  ["SUC","Sugestão a Projeto de Consolidação de Leis"],
  ["SUG","Sugestão"],
  ["SUM","Súmula"],
  ["TER","Termo de Implementação"],
  ["TVR","Ato de Concessão e Renovação de Concessão de Emissora de Rádio e Televisão"],
  ["VTS","Voto em Separado"],
]);
export const propositionTypeCodes = new Set(propositionTypes.map(([code]) => code));
